//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DAS.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DASParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IDASListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>progLine</c>
	/// labeled alternative in <see cref="DASParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgLine([NotNull] DASParser.ProgLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>progLine</c>
	/// labeled alternative in <see cref="DASParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgLine([NotNull] DASParser.ProgLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DASParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctions([NotNull] DASParser.FunctionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DASParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctions([NotNull] DASParser.FunctionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DASParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] DASParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DASParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] DASParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBlockLine</c>
	/// labeled alternative in <see cref="DASParser.fnBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnBlockLine([NotNull] DASParser.FnBlockLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBlockLine</c>
	/// labeled alternative in <see cref="DASParser.fnBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnBlockLine([NotNull] DASParser.FnBlockLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBodyLine</c>
	/// labeled alternative in <see cref="DASParser.fnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnBodyLine([NotNull] DASParser.FnBodyLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBodyLine</c>
	/// labeled alternative in <see cref="DASParser.fnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnBodyLine([NotNull] DASParser.FnBodyLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBodyLineMore</c>
	/// labeled alternative in <see cref="DASParser.fnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnBodyLineMore([NotNull] DASParser.FnBodyLineMoreContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBodyLineMore</c>
	/// labeled alternative in <see cref="DASParser.fnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnBodyLineMore([NotNull] DASParser.FnBodyLineMoreContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnExprLine</c>
	/// labeled alternative in <see cref="DASParser.fnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnReturnExprLine([NotNull] DASParser.FnReturnExprLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnExprLine</c>
	/// labeled alternative in <see cref="DASParser.fnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnReturnExprLine([NotNull] DASParser.FnReturnExprLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnLine</c>
	/// labeled alternative in <see cref="DASParser.fnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnReturnLine([NotNull] DASParser.FnReturnLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnLine</c>
	/// labeled alternative in <see cref="DASParser.fnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnReturnLine([NotNull] DASParser.FnReturnLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DASParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParams([NotNull] DASParser.ParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DASParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParams([NotNull] DASParser.ParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lineStmt</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineStmt([NotNull] DASParser.LineStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lineStmt</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineStmt([NotNull] DASParser.LineStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lineIf</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineIf([NotNull] DASParser.LineIfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lineIf</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineIf([NotNull] DASParser.LineIfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lineWhile</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineWhile([NotNull] DASParser.LineWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lineWhile</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineWhile([NotNull] DASParser.LineWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lineFor</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineFor([NotNull] DASParser.LineForContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lineFor</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineFor([NotNull] DASParser.LineForContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lineEOL</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineEOL([NotNull] DASParser.LineEOLContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lineEOL</c>
	/// labeled alternative in <see cref="DASParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineEOL([NotNull] DASParser.LineEOLContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcInvocLine</c>
	/// labeled alternative in <see cref="DASParser.funcInvoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncInvocLine([NotNull] DASParser.FuncInvocLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcInvocLine</c>
	/// labeled alternative in <see cref="DASParser.funcInvoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncInvocLine([NotNull] DASParser.FuncInvocLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtAtrib</c>
	/// labeled alternative in <see cref="DASParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtAtrib([NotNull] DASParser.StmtAtribContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtAtrib</c>
	/// labeled alternative in <see cref="DASParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtAtrib([NotNull] DASParser.StmtAtribContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtInput</c>
	/// labeled alternative in <see cref="DASParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtInput([NotNull] DASParser.StmtInputContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtInput</c>
	/// labeled alternative in <see cref="DASParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtInput([NotNull] DASParser.StmtInputContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtOutput</c>
	/// labeled alternative in <see cref="DASParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtOutput([NotNull] DASParser.StmtOutputContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtOutput</c>
	/// labeled alternative in <see cref="DASParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtOutput([NotNull] DASParser.StmtOutputContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lineFuncInvoc</c>
	/// labeled alternative in <see cref="DASParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineFuncInvoc([NotNull] DASParser.LineFuncInvocContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lineFuncInvoc</c>
	/// labeled alternative in <see cref="DASParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineFuncInvoc([NotNull] DASParser.LineFuncInvocContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>inputRead</c>
	/// labeled alternative in <see cref="DASParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputRead([NotNull] DASParser.InputReadContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>inputRead</c>
	/// labeled alternative in <see cref="DASParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputRead([NotNull] DASParser.InputReadContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>outputWriteVar</c>
	/// labeled alternative in <see cref="DASParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputWriteVar([NotNull] DASParser.OutputWriteVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>outputWriteVar</c>
	/// labeled alternative in <see cref="DASParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputWriteVar([NotNull] DASParser.OutputWriteVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>outputWriteStr</c>
	/// labeled alternative in <see cref="DASParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputWriteStr([NotNull] DASParser.OutputWriteStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>outputWriteStr</c>
	/// labeled alternative in <see cref="DASParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputWriteStr([NotNull] DASParser.OutputWriteStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>outputWriteExpr</c>
	/// labeled alternative in <see cref="DASParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputWriteExpr([NotNull] DASParser.OutputWriteExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>outputWriteExpr</c>
	/// labeled alternative in <see cref="DASParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputWriteExpr([NotNull] DASParser.OutputWriteExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>tipoNumero</c>
	/// labeled alternative in <see cref="DASParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipoNumero([NotNull] DASParser.TipoNumeroContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>tipoNumero</c>
	/// labeled alternative in <see cref="DASParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipoNumero([NotNull] DASParser.TipoNumeroContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>tipoTexto</c>
	/// labeled alternative in <see cref="DASParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipoTexto([NotNull] DASParser.TipoTextoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>tipoTexto</c>
	/// labeled alternative in <see cref="DASParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipoTexto([NotNull] DASParser.TipoTextoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ifstIf</c>
	/// labeled alternative in <see cref="DASParser.ifst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfstIf([NotNull] DASParser.IfstIfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ifstIf</c>
	/// labeled alternative in <see cref="DASParser.ifst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfstIf([NotNull] DASParser.IfstIfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ifstIfElse</c>
	/// labeled alternative in <see cref="DASParser.ifst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfstIfElse([NotNull] DASParser.IfstIfElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ifstIfElse</c>
	/// labeled alternative in <see cref="DASParser.ifst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfstIfElse([NotNull] DASParser.IfstIfElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>whilestWhile</c>
	/// labeled alternative in <see cref="DASParser.whilest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhilestWhile([NotNull] DASParser.WhilestWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>whilestWhile</c>
	/// labeled alternative in <see cref="DASParser.whilest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhilestWhile([NotNull] DASParser.WhilestWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>whilestDoWhile</c>
	/// labeled alternative in <see cref="DASParser.whilest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhilestDoWhile([NotNull] DASParser.WhilestDoWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>whilestDoWhile</c>
	/// labeled alternative in <see cref="DASParser.whilest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhilestDoWhile([NotNull] DASParser.WhilestDoWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>forstFor</c>
	/// labeled alternative in <see cref="DASParser.forst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForstFor([NotNull] DASParser.ForstForContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>forstFor</c>
	/// labeled alternative in <see cref="DASParser.forst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForstFor([NotNull] DASParser.ForstForContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>blockLine</c>
	/// labeled alternative in <see cref="DASParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockLine([NotNull] DASParser.BlockLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>blockLine</c>
	/// labeled alternative in <see cref="DASParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockLine([NotNull] DASParser.BlockLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>condRelop</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondRelop([NotNull] DASParser.CondRelopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>condRelop</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondRelop([NotNull] DASParser.CondRelopContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>condExpr</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondExpr([NotNull] DASParser.CondExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>condExpr</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondExpr([NotNull] DASParser.CondExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>condAnd</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondAnd([NotNull] DASParser.CondAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>condAnd</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondAnd([NotNull] DASParser.CondAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>condOr</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondOr([NotNull] DASParser.CondOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>condOr</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondOr([NotNull] DASParser.CondOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>condNot</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondNot([NotNull] DASParser.CondNotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>condNot</c>
	/// labeled alternative in <see cref="DASParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondNot([NotNull] DASParser.CondNotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>atribVar</c>
	/// labeled alternative in <see cref="DASParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtribVar([NotNull] DASParser.AtribVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atribVar</c>
	/// labeled alternative in <see cref="DASParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtribVar([NotNull] DASParser.AtribVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>atribVarStr</c>
	/// labeled alternative in <see cref="DASParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtribVarStr([NotNull] DASParser.AtribVarStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atribVarStr</c>
	/// labeled alternative in <see cref="DASParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtribVarStr([NotNull] DASParser.AtribVarStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exprPlus</c>
	/// labeled alternative in <see cref="DASParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprPlus([NotNull] DASParser.ExprPlusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exprPlus</c>
	/// labeled alternative in <see cref="DASParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprPlus([NotNull] DASParser.ExprPlusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exprMinus</c>
	/// labeled alternative in <see cref="DASParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprMinus([NotNull] DASParser.ExprMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exprMinus</c>
	/// labeled alternative in <see cref="DASParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprMinus([NotNull] DASParser.ExprMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exprTerm</c>
	/// labeled alternative in <see cref="DASParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprTerm([NotNull] DASParser.ExprTermContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exprTerm</c>
	/// labeled alternative in <see cref="DASParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprTerm([NotNull] DASParser.ExprTermContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>termMult</c>
	/// labeled alternative in <see cref="DASParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermMult([NotNull] DASParser.TermMultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>termMult</c>
	/// labeled alternative in <see cref="DASParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermMult([NotNull] DASParser.TermMultContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>termDiv</c>
	/// labeled alternative in <see cref="DASParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermDiv([NotNull] DASParser.TermDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>termDiv</c>
	/// labeled alternative in <see cref="DASParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermDiv([NotNull] DASParser.TermDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>termFactor</c>
	/// labeled alternative in <see cref="DASParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermFactor([NotNull] DASParser.TermFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>termFactor</c>
	/// labeled alternative in <see cref="DASParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermFactor([NotNull] DASParser.TermFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factorExpr</c>
	/// labeled alternative in <see cref="DASParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactorExpr([NotNull] DASParser.FactorExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factorExpr</c>
	/// labeled alternative in <see cref="DASParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactorExpr([NotNull] DASParser.FactorExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factorVar</c>
	/// labeled alternative in <see cref="DASParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactorVar([NotNull] DASParser.FactorVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factorVar</c>
	/// labeled alternative in <see cref="DASParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactorVar([NotNull] DASParser.FactorVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factorNum</c>
	/// labeled alternative in <see cref="DASParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactorNum([NotNull] DASParser.FactorNumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factorNum</c>
	/// labeled alternative in <see cref="DASParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactorNum([NotNull] DASParser.FactorNumContext context);
}
